name: Partial Pipeline - Before Merge
trigger: change
jobs:
  partial:
    image: hub.byted.org/base/ci_nodejs_22:297bea689b0966fcbdb2daff6b39ed6b
    steps:
      - name: Init
        commands:
          - npm config set registry https://registry.npmjs.org/
      - name: Install
        commands:
          - node common/scripts/install-run-rush.js update
      - name: Build
        commands:
          - node common/scripts/install-run-rush.js build --to git:origin/$CI_EVENT_CHANGE_TARGET_BRANCH
